app:
    resource: "@AppBundle/Controller/"
    type:     annotation
auth:
    path:     /authenticate/
    defaults: { _controller: AppBundle:Auth:index }
pollmessages:
    path:     /pollmessages/
    defaults: { _controller: AppBundle:Default:pollmessages }
postmessage:
    path:     /postmessage/
    defaults: { _controller: AppBundle:Default:postmessage }
